spring.application.name=ANDROID_PROJECT

server.port=8089

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=PROJETSGBD
spring.datasource.password=123456
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none

server.address=0.0.0.0